  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/db_ban_hang?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      username: admin
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialization-mode: always

    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      generate-ddl: true
      show-sql: true
      hibernate:
        ddl-auto: update